### ISSUE TITLE
Third Virial Coefficient of uv-BH implementation returns NaN

### ISSUE THREAD

**Issue by anreimer** [feos-org/feos#123] opened 2023-01-26 16:21 UTC
Example in Python (as in lj_models.ipynb):

```python
sigma = 3.7039
eps_k = 150.03
parameters = UVParameters.new_simple(12.0, 6.0, sigma, eps_k)
uvtheory_bh = EquationOfState.uvtheory(parameters, perturbation=Perturbation.BarkerHenderson)
uvtheory_bh.third_virial_coefficient(6 * KELVIN)
```

returns  _NaN_ m³/mol²
Works for uv-B3 & uv-WCA implementation.

**Comment by g-bauer** [comment] 2023-01-26 16:59
The u-fraction returns `NaN`. The `reduced_density` is zero and `reduced_density.powf(a)` (see [here](https://github.com/feos-org/feos/blob/main/src/uvtheory/eos/attractive_perturbation_bh.rs#L128)) returns `NaN`. Looks like this is a bug in num-dual.
This can be reproduced with:

```python
from num_dual import Dual64

Dual64.from_re(0.0)**1.0 # 0 + [0]ε
Dual64.from_re(0.0)**2.0 # 0 + [0]ε
Dual64.from_re(0.0)**1.5 # NaN + [NaN]ε
```

**Comment by longemen3000** [comment] 2023-01-26 17:38
Related:
https://github.com/autodiff/autodiff/issues/242#issuecomment-1221992874

https://github.com/JuliaDiff/ForwardDiff.jl/issues/480

**Comment by prehner** [comment] 2023-03-17 08:44
Since this seems to be caused by the uv-BH model actually not being differentiable sufficiently, there is nothing really to solve here, and I'm closing this issue.

**Closed by prehner** 2023-03-17 08:44 UTC
